/**
 * Personalized flyer (poster) email — Aviance founding-client one-pager.
 *
 * Used as the DAY-3 follow-up for every lead: the plain-text day-0 opener
 * wins inbox placement and starts the relationship; three days later the
 * lead gets this designed poster — personalized with their name and company —
 * threaded into the same conversation.
 *
 * Email-safe: table layout, inline styles, hosted logo image (no data URIs),
 * web-safe font fallbacks (Archivo Black/Space Mono degrade to Arial Black /
 * Courier New in clients that don't load webfonts).
 */

const LOGO_URL = 'https://email-distributor.vercel.app/api/logo';
const SITE_URL = 'https://www.aviance.online';

const HEAD = "font-family:'Archivo Black','Arial Black',Arial,sans-serif;";
const MONO = "font-family:'Space Mono','Courier New',monospace;";

export function flyerHtml(lead) {
  const name = (lead.first_name || '').trim();
  const company = lead.company_name || lead.company || 'your company';
  const hi = name ? `Hi ${name},` : 'Hi,';

  return `<div style="font-family:Arial,sans-serif;font-size:15px;color:#222;line-height:1.6;">${hi}<br><br>We have yet to be properly introduced — we're Aviance. We book qualified sales calls straight onto the calendars of firms like ${escapeHtml(company)}. Rather than pitch you, here is exactly what we do and what we guarantee, in writing.<br><br></div>
<div style="background:#EFEDE8;padding:14px 0;"><table role="presentation" width="620" cellpadding="0" cellspacing="0" align="center" style="max-width:620px;width:100%;background:#FFFFFF;">
<tbody>
<tr><td style="padding:24px 28px 20px 28px;background:#FFFFFF;border-bottom:4px solid #141414;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tbody><tr><td style="vertical-align:middle;"><img src="${LOGO_URL}" alt="Aviance" width="48" height="48" style="vertical-align:middle;margin-right:12px;"><span style="${HEAD}font-size:27px;letter-spacing:2px;color:#141414;vertical-align:middle;">AVIANCE</span></td><td align="right" style="${MONO}font-size:10px;font-weight:700;letter-spacing:1px;color:#8A8A85;">PREPARED&nbsp;FOR<br><span style="color:#E0290F;">${escapeHtml(String(company).toUpperCase())}</span></td></tr></tbody></table></td></tr>
<tr><td style="background:#E0290F;padding:9px 28px;"><span style="${MONO}font-size:11px;font-weight:700;letter-spacing:3px;color:#FFFFFF;">GUARANTEED&nbsp;BOOKED&nbsp;SALES&nbsp;CALLS&nbsp;—&nbsp;IN&nbsp;WRITING</span></td></tr>
<tr><td style="padding:30px 28px 4px 28px;background:#FFFFFF;"><div style="${MONO}font-size:11px;font-weight:700;letter-spacing:3px;color:#E0290F;margin-bottom:12px;">00&nbsp;/&nbsp;THE&nbsp;PROBLEM</div><div style="${HEAD}font-size:30px;line-height:1.15;color:#141414;text-transform:uppercase;">Referrals are great&nbsp;—<br>until the month<br>they <span style="color:#E0290F;">aren't.</span></div><p style="font-size:15px;line-height:1.7;color:#3A3A3A;margin:14px 0 6px 0;">Most firms like ${escapeHtml(company)} win nearly all their new business through word of mouth. Which works right up until it doesn't — and then sales stalls for a quarter.</p></td></tr>
<tr><td style="padding:20px 28px 4px 28px;background:#FFFFFF;"><div style="${MONO}font-size:11px;font-weight:700;letter-spacing:3px;color:#E0290F;margin-bottom:12px;">01&nbsp;/&nbsp;WHAT&nbsp;WE&nbsp;DO</div><p style="font-size:15px;line-height:1.7;color:#3A3A3A;margin:0;"><strong style="color:#141414;">We don't sell emails. We sell booked sales calls — on your calendar.</strong> Domains, warmed inboxes, verified lists, copywriting, sending and reply handling — all run by us. You show up and close.</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:16px;"><tbody><tr><td width="33%" style="background:#141414;padding:14px 8px;text-align:center;"><div style="${HEAD}font-size:25px;color:#FFFFFF;">3<span style="font-size:14px;color:#E0290F;">WK</span></div><div style="${MONO}font-size:9px;font-weight:700;letter-spacing:1px;color:#B9B9B4;margin-top:4px;">TO&nbsp;LIVE&nbsp;·&nbsp;GUARANTEED</div></td><td width="5"></td><td width="33%" style="background:#E0290F;padding:14px 8px;text-align:center;"><div style="${HEAD}font-size:25px;color:#FFFFFF;">10–50</div><div style="${MONO}font-size:9px;font-weight:700;letter-spacing:1px;color:#FFD9D2;margin-top:4px;">CALLS&nbsp;/&nbsp;MONTH</div></td><td width="5"></td><td width="33%" style="background:#141414;padding:14px 8px;text-align:center;"><div style="${HEAD}font-size:25px;color:#FFFFFF;">$0</div><div style="${MONO}font-size:9px;font-weight:700;letter-spacing:1px;color:#B9B9B4;margin-top:4px;">SETUP&nbsp;FEES&nbsp;·&nbsp;EVER</div></td></tr></tbody></table></td></tr>
<tr><td style="padding:24px 28px 4px 28px;background:#FFFFFF;"><div style="${MONO}font-size:11px;font-weight:700;letter-spacing:3px;color:#E0290F;margin-bottom:12px;">02&nbsp;/&nbsp;WHAT&nbsp;WE&nbsp;PUT&nbsp;IN&nbsp;WRITING</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="font-size:14px;line-height:1.55;color:#141414;"><tbody><tr><td style="padding:8px 0;border-bottom:2px solid #141414;"><span style="color:#E0290F;font-weight:800;">✓</span>&nbsp;&nbsp;A guaranteed number of booked calls, every month</td></tr><tr><td style="padding:8px 0;border-bottom:2px solid #141414;"><span style="color:#E0290F;font-weight:800;">✓</span>&nbsp;&nbsp;Miss the number? The shortfall rolls over — we owe you those calls</td></tr><tr><td style="padding:8px 0;border-bottom:2px solid #141414;"><span style="color:#E0290F;font-weight:800;">✓</span>&nbsp;&nbsp;No-shows replaced free — only calls that happen count</td></tr><tr><td style="padding:8px 0;border-bottom:2px solid #141414;"><span style="color:#E0290F;font-weight:800;">✓</span>&nbsp;&nbsp;Not live in 3 weeks? Your next month is free</td></tr><tr><td style="padding:8px 0;"><span style="color:#E0290F;font-weight:800;">✓</span>&nbsp;&nbsp;Month-to-month · you approve every email before it sends</td></tr></tbody></table></td></tr>
<tr><td style="padding:24px 28px 10px 28px;background:#FFFFFF;"><div style="${MONO}font-size:11px;font-weight:700;letter-spacing:3px;color:#E0290F;margin-bottom:12px;">03&nbsp;/&nbsp;FOUNDING&nbsp;CLIENT&nbsp;RATES</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#141414;"><tbody><tr><td style="padding:18px 22px;"><div style="${HEAD}font-size:19px;line-height:1.25;color:#FFFFFF;text-transform:uppercase;">20% off Growth &amp; Scale —<br><span style="color:#E0290F;">locked in for life.</span></div><p style="font-size:13px;line-height:1.6;color:#B9B9B4;margin:8px 0 0 0;">3 founding clients only, in exchange for a case study when we deliver. When the slots fill, these rates are gone for good.</p></td></tr></tbody></table>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:12px;border:2px solid #DDD9D2;"><tbody><tr><td style="padding:12px 16px;"><span style="${HEAD}font-size:15px;color:#141414;">STARTER</span><span style="${MONO}font-size:9px;font-weight:700;color:#8A8A85;">&nbsp;&nbsp;10&nbsp;CALLS/MO</span></td><td align="right" style="padding:12px 16px;"><span style="${HEAD}font-size:16px;color:#5A5A57;">$2,497</span><span style="font-size:11px;color:#8A8A85;">/mo</span><div style="${MONO}font-size:9px;font-weight:700;color:#8A8A85;">$250&nbsp;PER&nbsp;CALL</div></td></tr></tbody></table>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:10px;border:4px solid #E0290F;"><tbody><tr><td colspan="2" style="background:#E0290F;padding:7px 16px;${MONO}font-size:10px;font-weight:700;letter-spacing:2px;color:#FFFFFF;">★&nbsp;MOST&nbsp;POPULAR&nbsp;—&nbsp;FOUNDING&nbsp;RATE</td></tr><tr><td style="padding:16px 16px 4px 16px;"><span style="${HEAD}font-size:22px;color:#141414;">GROWTH</span><span style="${MONO}font-size:9px;font-weight:700;color:#8A8A85;">&nbsp;&nbsp;20&nbsp;CALLS/MO</span></td><td align="right" style="padding:16px 16px 4px 16px;"><span style="font-size:13px;color:#9A9A95;text-decoration:line-through;">$3,997</span>&nbsp;<span style="${HEAD}font-size:27px;color:#E0290F;">$2,997</span><span style="font-size:12px;color:#8A8A85;">/mo</span><div style="${MONO}font-size:9px;font-weight:700;color:#E0290F;">$150/CALL&nbsp;—&nbsp;LOWEST&nbsp;OF&nbsp;ANY&nbsp;PLAN</div></td></tr><tr><td colspan="2" style="padding:2px 16px 14px 16px;font-size:13px;line-height:1.6;color:#3A3A3A;">Twice the calls of Starter for <strong style="color:#141414;">$500 more</strong>. Dedicated strategist, 3 campaign segments, monthly sequence rewrites.</td></tr></tbody></table>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:10px;border:2px solid #141414;"><tbody><tr><td style="padding:13px 16px 2px 16px;"><span style="${HEAD}font-size:16px;color:#141414;">SCALE</span><span style="${MONO}font-size:9px;font-weight:700;color:#8A8A85;">&nbsp;&nbsp;50&nbsp;CALLS/MO&nbsp;·&nbsp;FOUNDING&nbsp;RATE</span></td><td align="right" style="padding:13px 16px 2px 16px;"><span style="font-size:12px;color:#9A9A95;text-decoration:line-through;">$8,497</span>&nbsp;<span style="${HEAD}font-size:19px;color:#141414;">$6,997</span><span style="font-size:11px;color:#8A8A85;">/mo</span><div style="${MONO}font-size:9px;font-weight:700;color:#8A8A85;">$140&nbsp;PER&nbsp;CALL</div></td></tr><tr><td colspan="2" style="padding:0 16px 12px 16px;font-size:12px;line-height:1.6;color:#5A5A57;">More than two booked calls every working day. Unlimited segments, multi-market expansion.</td></tr></tbody></table>
<div style="${MONO}font-size:9px;font-weight:700;letter-spacing:1px;color:#8A8A85;margin-top:10px;">BILLED&nbsp;MONTHLY&nbsp;IN&nbsp;ADVANCE&nbsp;·&nbsp;NO&nbsp;SETUP&nbsp;FEES&nbsp;·&nbsp;CANCEL&nbsp;WITH&nbsp;14&nbsp;DAYS'&nbsp;NOTICE</div></td></tr>
<tr><td style="padding:22px 28px 28px 28px;background:#FFFFFF;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tbody><tr><td align="center" style="background:#E0290F;"><a href="${SITE_URL}" style="display:block;padding:17px 0;color:#FFFFFF;${HEAD}font-size:16px;letter-spacing:2px;text-decoration:none;">BOOK&nbsp;A&nbsp;15-MINUTE&nbsp;CALL&nbsp;→</a></td></tr></tbody></table><p style="font-size:12px;line-height:1.6;color:#8A8A85;text-align:center;margin:12px 0 0 0;">No pitch deck, no pressure — we'll tell you on the call if outbound is wrong for your offer.<br>Or simply reply to this email and we'll take it from there.</p></td></tr>
<tr><td style="padding:16px 28px;background:#141414;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tbody><tr><td style="${MONO}font-size:9px;font-weight:700;letter-spacing:2px;color:#B9B9B4;">AVIANCE&nbsp;—&nbsp;GUARANTEED&nbsp;BOOKED&nbsp;SALES&nbsp;CALLS</td><td align="right" style="${MONO}font-size:10px;font-weight:700;"><a href="${SITE_URL}" style="color:#E0290F;text-decoration:underline;">www.aviance.online</a></td></tr></tbody></table><div style="font-size:9px;color:#7A7A75;margin-top:6px;">Not the right fit? Just reply STOP and we won't email you again.</div></td></tr>
</tbody></table></div>`;
}

function escapeHtml(s) {
  return String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
